version: "3.9"

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: "./frontend"
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - docker
  backend:
    build:
      dockerfile: Dockerfile
      context: "./server"
    container_name: backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - docker

networks:
  docker:
    external: true
